import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { ThemeProvider } from '@/components/theme-provider'
import { Sidebar } from '@/components/ui/modern-side-bar'
import { UploadDialogTriggerProvider } from '@/hooks/use-upload-dialog-trigger'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider>
					<UploadDialogTriggerProvider>
						<div className="flex min-h-dvh items-stretch bg-background text-foreground">
							<Sidebar />
							<main className="min-h-dvh min-w-0 flex-1">{children}</main>
						</div>
					</UploadDialogTriggerProvider>
				</ThemeProvider>
			</body>
		</html>
	)
}
